services:
  - type: web
    runtime: static
    name: boag-dashboard
    buildCommand: bash build.sh
    staticPublishPath: ./public
    autoDeployTrigger: commit
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /index.html
        name: Cache-Control
        value: no-cache
